using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace api_server.Utility
{
    public static class AppConfiguration
    {
        public const int pageSize = 6;

        public const int pageSizeOpinions = 6;

        public enum AppRole
        {
            Admin,
            Programmer,
            Company
            
        }

        public const string autogeneratedMessage = @"{""blocks"":[{""key"":""db8sh"",""text"":""Wiadmość wygenerowania automatycznie:"",""type"":""header-three"",""depth"":0,""inlineStyleRanges"":[{""offset"":0,""length"":37,""style"":""BOLD""},{""offset"":0,""length"":37,""style"":""fontfamily-Georgia""},{""offset"":0,""length"":37,""style"":""fontsize-16""},{""offset"":0,""length"":37,""style"":""color-rgb(184,49,47)""}],""entityRanges"":[],""data"":{}},{""key"":""6cj2k"",""text"":""Twoja aplikacja na ofertę o tytule TITLE została odrzucona przez twórcę zgłoszenia."",""type"":""unstyled"",""depth"":0,""inlineStyleRanges"":[{""offset"":0,""length"":83,""style"":""fontfamily-Georgia""},{""offset"":35,""length"":SIZE,""style"":""BOLD""},{""offset"":35,""length"":SIZE,""style"":""ITALIC""}],""entityRanges"":[],""data"":{}}],""entityMap"":{}}";
   }
}
